# Ubuntu 14.04
ubuntu-trusty:
  image: ubuntu:trusty
  variables:
    CI_ROS_DISTRO: indigo
    UBUNTU_DISTRO: trusty

  before_script:
    - rm -rf ../src
    - sudo apt-get update
    - sudo apt-get install -qq -y apt-transport-https sed wget unzip > /dev/null
    - source .gitlab-ci/prepare.sh
    - sudo ./setup.sh $UBUNTU_DISTRO $CI_ROS_DISTRO > /dev/null
    - setup_apt
    - sudo apt-get install -qq -y python-catkin-tools v4r > /dev/null
    - rosdep update > /dev/null
    - rosdep install --from-paths . -i -y -r --rosdistro $CI_ROS_DISTRO > /dev/null
    - add_v4r_yaml
    
  stage: build
  script:
    - old_dir=`pwd`
    - mkdir -p /tmp/src
    - cp  -r * /tmp/src/
    - cd /tmp/
    - source /opt/ros/${CI_ROS_DISTRO}/setup.sh
    - catkin init
    - catkin build
    - cd $old_dir
    - rm -rf /tmp/src

# Ubuntu 14.04 debian package generation
ubuntu-trusty-build-package:
  image: ubuntu:trusty
  variables:
    CI_ROS_DISTRO: indigo
    UBUNTU_DISTRO: trusty

  before_script:
    - sudo apt-get update
    - sudo apt-get install -qq -y apt-transport-https sed wget unzip > /dev/null
    - source .gitlab-ci/prepare.sh
    - sudo ./setup.sh $UBUNTU_DISTRO $CI_ROS_DISTRO > /dev/null
    - setup_apt
    - sudo apt-get install -q -y python-bloom devscripts v4r > /dev/null
    - rosdep update > /dev/null
    - rosdep install --from-paths . -i -y -r --rosdistro $CI_ROS_DISTRO > /dev/null
    - add_v4r_yaml

  stage: build
  script:
    - ls *
    - rm -rf build
    - source .gitlab-ci/release.sh
    - show_info
    - mkdir .build
    - release_package
    - mv .build build

  # This stage is only executed for new tags
#  only:
#    - tags
#    - release@root/v4r

  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - build/*

# Ubuntu 16.04
ubuntu-xenial:
  image: ubuntu:xenial
  variables:
    CI_ROS_DISTRO: kinetic
    UBUNTU_DISTRO: xenial

  before_script:
    - apt-get update
    - apt-get install -qq -y apt-transport-https sed wget unzip sudo > /dev/null
    - source .gitlab-ci/prepare.sh
    - sudo ./setup.sh $UBUNTU_DISTRO $CI_ROS_DISTRO > /dev/null
    - setup_apt
    - sudo apt-get install -qq -y python-catkin-tools > /dev/null
    - wget https://rgit.acin.tuwien.ac.at/markus-bajones/v4r/-/jobs/1658/artifacts/download
    - unzip download
    - dpkg -i build/v4r*deb || echo "dpkg"
    - apt-get install -f -y > /dev/null
    - rosdep update > /dev/null
    - rosdep install --from-paths . -i -y -r --rosdistro $CI_ROS_DISTRO > /dev/null
    - add_v4r_yaml
    
  stage: build
  script:
    - old_dir=`pwd`
    - mkdir -p /tmp/src
    - cp  -r * /tmp/src/
    - cd /tmp/
    - source /opt/ros/${CI_ROS_DISTRO}/setup.sh
    - catkin init
    - catkin build
    - cd $old_dir
    - rm -rf /tmp/src


# Ubuntu 16.04 debian package generation
ubuntu-xenial-build-package:
  image: ubuntu:xenial
  variables:
    CI_ROS_DISTRO: kinetic
    UBUNTU_DISTRO: xenial

  before_script:
    - echo $CI_ROS_DISTRO
    - echo ${CI_ROS_DISTRO}
    - apt-get update
    - apt-get install -qq -y apt-transport-https sed wget unzip sudo > /dev/null
    - source .gitlab-ci/prepare.sh
    - sudo ./setup.sh $UBUNTU_DISTRO $CI_ROS_DISTRO > /dev/null
    - setup_apt
    - sudo apt-get install -q -y python-bloom devscripts > /dev/null
    - wget https://rgit.acin.tuwien.ac.at/markus-bajones/v4r/-/jobs/1658/artifacts/download
    - unzip download
    - dpkg -i build/v4r*deb || echo "dpkg"
    - apt-get install -f -y > /dev/null
    - rosdep update > /dev/null
    - rosdep install --from-paths . -i -y -r --rosdistro $CI_ROS_DISTRO > /dev/null
    - add_v4r_yaml

  stage: build
  script:
    - ls *
    - rm -rf build
    - source .gitlab-ci/release.sh
    - show_info
    - mkdir .build
    - release_package
    - mv .build build

  # This stage is only executed for new tags
#  only:
#    - tags
#    - release@root/v4r

  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - build/*

