sensor_msgs/PointCloud2 cloud
std_msgs/Int32MultiArray[] clusters_indices
---
std_msgs/Int32MultiArray[] clusters_indices

# classification results for each cluster
StringArray[] category_ids 

# confidence for each cluster's classification
std_msgs/Float32MultiArray[] confidences

# centroid of the cluster
geometry_msgs/Point32[] centroid

# bounding box of the cluster
geometry_msgs/Polygon[] bbox # 8-point bounding boxes of the objects

# point cloud of the cluster 
sensor_msgs/PointCloud2[] cloud
