sensor_msgs/PointCloud2 cloud
std_msgs/Int32MultiArray[] clusters_indices
---
std_msgs/Int32MultiArray[] clusters_indices

# classification result for clusters
v4r_object_perception_msgs/classification[] class_results

# centroid of the cluster
geometry_msgs/Point32[] centroid

# bounding box of the cluster
v4r_object_perception_msgs/BBox[] bbox

# point cloud of the cluster 
sensor_msgs/PointCloud2[] cloud
